<a href="https://colab.research.google.com/github/prathwishshetty/Regression/blob/master/Linear%20Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression in Python  
Writing a Python code whose input is a training datset ${(x^1,y^1),...,(x^N,y^N)}$ and its output is the weight vector $\theta$ in the linear regression model $y = \theta^t\phi(x)$, for a given nonlinear mapping $\phi(·)$  
  
We will first install the dependencies of the program

In [0]:
from numpy import array, dot, transpose
import pandas as pd
from numpy.linalg import inv
from scipy import stats
import scipy.io as spio
import os
import numpy as np

#### Creating a function for Closed Form of Linear Regression  
We know that the closed form of solving a linear regression in a matrix form is as follows, $\theta=(x^Tx)^{-1} x^T y$. The same has been implemented below as a python function 

In [0]:
def linear_regression_closed(x,y):
    x = np.array(x)
    ones = np.ones(len(x))
    x = np.column_stack((ones,x))
    y = np.array(y)    
    theta = dot(dot(inv(dot(transpose(x),x)), transpose(x)), y)      
    return theta

#### Creating a function for Linear Regression with mini-batch Gradient Descent
Function for linear regression in a mini batch gradient descent

In [0]:
def batch_gradient_descent(x, y, m,alpha,numIterations):
    x = np.array(x)
    ones = np.ones(len(x))
    x = np.column_stack((ones,x))
    y = np.array(y)
    theta = np.zeros(x.shape[1])
    for iter in range(numIterations):
        for i in range(0,len(x),m):
            x_new=x[i:i+m]
            y_new=y[i:i+m]
            x_newT=x_new.transpose()
            hypothesis = np.dot(x_new, theta)
            loss = hypothesis - y_new
            J = np.sum(loss ** 2) / (2 * m)  # cost 
            #print(iter,i,J)
            gradient = np.dot(x_newT, loss) / m         
            theta = theta - alpha * gradient  # update
    return theta

### Creating a function for ridge regression in closed form
Function for ridge regression in closed form

In [0]:
def ridge_regression(x,y,lamb):
    x = np.array(x)
    ones = np.ones(len(x))
    x = np.column_stack((ones,x))
    y = np.array(y) 
    I=np.identity(x.shape[1])
    theta = dot(dot(inv(dot(transpose(x),x)+(lamb*I)), transpose(x)), y)
    return theta

### Creating a function for Ridge Regression with batch gradient descent 
Function for ridge regression in gradient descent

In [0]:
def batch_ridge_gradient_descent(x, y, m,alpha,numIterations,L):
    intercept = np.ones(len(x))
    X = np.append(intercept, x)
    X = np.reshape(X,(x.shape[0],x.shape[1]+1))
    x = stats.zscore(X, axis=0)
    y = stats.zscore(y)
    x = np.array(x)
    y = np.array(y)
    theta = np.zeros(x.shape[1])
    for iter in range(numIterations):
        for i in range(0,len(x),m):
            x_new=x[i:i+m]
            y_new=y[i:i+m]
            x_newT=x_new.transpose()
            hypothesis = np.dot(x_new, theta)
            loss = hypothesis - y_new
            J =  J = np.sum(loss ** 2) / (2 * m) # cost 
            print(iter,i,J)
            gradient = np.dot(x_newT, loss) / m         
            theta = theta - alpha * (gradient + (L/m)*theta)  # update
    return theta

Test the quality of the models that have been created

In [0]:
def model_test(x,y,theta_test):
    xt = np.array(x)
    ones = np.ones(len(xt))
    xt = np.column_stack((ones,xt))
    yt = np.array(y)
    loss = np.sum((np.dot(xt, theta_test) - yt)**2)
    return loss

Creating a training dataset by using the random number generator of the `numpy` package

In [0]:
np.random.seed(0)
xTrain=np.random.rand(200,)
yTrain=np.random.rand(200,)
xTest=np.random.rand(200,)
yTest=np.random.rand(200,)

Creating a $2^{nd}, 3^{rd}$ and $5^{th}$ degree polynomial of the type:
* $y=x+x^2$
* $y=x+x^2+x^3$
* $y=x+x^2+x^3+x^4+x^5$

In [0]:
xTrain_n2 = np.column_stack((xTrain,xTrain**2))
xTrain_n3 = np.column_stack((xTrain,xTrain**2,xTrain**3))
xTrain_n5 = np.column_stack((xTrain,xTrain**2,xTrain**3,xTrain**4,xTrain**5))
xTest_n2 = np.column_stack((xTest,xTest**2))

xTest_n3 = np.column_stack((xTest,xTest**2,xTest**3))
xTest_n5 = np.column_stack((xTest,xTest**2,xTest**3,xTest**4,xTest**5))

In [9]:
print("2nd degree polynomial")
theta_c_2=linear_regression_closed(xTrain_n2, yTrain)
print(theta_c_2)

#Calculate the training error
training_error_c_2=model_test(xTrain_n2,yTrain,linear_regression_closed(xTrain_n2, yTrain))
print("Training Error:",training_error_c_2)

test_error_c_2=model_test(xTest_n2,yTrain,linear_regression_closed(xTrain_n2, yTrain))
print("Test Error:",test_error_c_2)

print("")
print("")
print("3rd degree polynomial")
theta_c_3=linear_regression_closed(xTrain_n3, yTrain)
print(theta_c_3)

#Calculate the training error
training_error_c_3=model_test(xTrain_n3,yTrain,linear_regression_closed(xTrain_n3, yTrain))
print("Training Error:",training_error_c_3)

test_error_c_3=model_test(xTest_n3,yTrain,linear_regression_closed(xTrain_n3, yTrain))
print("Test Error:",test_error_c_3)
print("")
print("")
print("5th degree polynomial")
theta_c_5=linear_regression_closed(xTrain_n5, yTrain)
print(theta_c_5)

#Calculate the training error
training_error_c_5=model_test(xTrain_n5,yTrain,linear_regression_closed(xTrain_n5, yTrain))
print("Training Error:",training_error_c_5)

test_error_c_5=model_test(xTest_n5,yTrain,linear_regression_closed(xTrain_n5, yTrain))
print("Test Error:",test_error_c_5)

2nd degree polynomial
[ 0.5680825  -0.35216161  0.30010179]
Training Error: 17.119520790745174
Test Error: 17.29651245246555


3rd degree polynomial
[ 0.53312554  0.06678217 -0.73162787  0.68065069]
Training Error: 17.08687916700004
Test Error: 17.090268079181303


5th degree polynomial
[  0.6476598   -2.47009181  12.62284967 -25.99437832  22.08020129
  -6.27041737]
Training Error: 16.89635155393961
Test Error: 17.58998000476202


In [10]:
print("2nd degree polynomial")
theta_c_2=linear_regression_closed(xTrain_n2, yTrain)
print(theta_c_2)

#Calculate the training error
training_error_c_2=model_test(xTrain_n2,yTrain,linear_regression_closed(xTrain_n2, yTrain))
print("Training Error:",training_error_c_2)

test_error_c_2=model_test(xTest_n2,yTrain,linear_regression_closed(xTrain_n2, yTrain))
print("Test Error:",test_error_c_2)

print("")
print("")
print("3rd degree polynomial")
theta_c_3=linear_regression_closed(xTrain_n3, yTrain)
print(theta_c_3)

#Calculate the training error
training_error_c_3=model_test(xTrain_n3,yTrain,linear_regression_closed(xTrain_n3, yTrain))
print("Training Error:",training_error_c_3)

test_error_c_3=model_test(xTest_n3,yTrain,linear_regression_closed(xTrain_n3, yTrain))
print("Test Error:",test_error_c_3)
print("")
print("")
print("5th degree polynomial")
theta_c_5=linear_regression_closed(xTrain_n5, yTrain)
print(theta_c_5)

#Calculate the training error
training_error_c_5=model_test(xTrain_n5,yTrain,linear_regression_closed(xTrain_n5, yTrain))
print("Training Error:",training_error_c_5)

test_error_c_5=model_test(xTest_n5,yTrain,linear_regression_closed(xTrain_n5, yTrain))
print("Test Error:",test_error_c_5)

2nd degree polynomial
[ 0.5680825  -0.35216161  0.30010179]
Training Error: 17.119520790745174
Test Error: 17.29651245246555


3rd degree polynomial
[ 0.53312554  0.06678217 -0.73162787  0.68065069]
Training Error: 17.08687916700004
Test Error: 17.090268079181303


5th degree polynomial
[  0.6476598   -2.47009181  12.62284967 -25.99437832  22.08020129
  -6.27041737]
Training Error: 16.89635155393961
Test Error: 17.58998000476202
